### PR TITLE
chore(deps): update github.com/coder/envbuilder to v1.0.2

### PR DESCRIPTION
**Pull request by mafredri**
Preparing to release v0.0.10.

### CODE REVIEW

**Review by dannykopping — APPROVED** [review]
LGTM
I think your description is referencing the wrong version though?

**Comment by mafredri** [comment]
> LGTM I think your description is referencing the wrong version though?

It's the version of the provider (currently v0.0.9).

**Comment by dannykopping** [comment]
> > LGTM I think your description is referencing the wrong version though?
> 
> It's the version of the provider (currently v0.0.9).

Gotcha. Should we consider major-version bumping the provider too?

**Comment by mafredri** [comment]
> Gotcha. Should we consider major-version bumping the provider too?

Thoughts @bpmct? I'd like to keep it `v0` for the time being until we see it has more of a proven track-record. Our `terraform-provider-coderd` provider is also `v0` currently and it's about the same age. I don't know about it's future plans though.

**Review by mtojek — APPROVED** [review]
Congrats!!

**Pull request merged**
